name: Terraform CI/CD

on:
  push:
    branches:
      - terraform-dev
      

jobs:

  # ==========================================
  # FEATURE BRANCH - PLAN ONLY
  # ==========================================
  terraform-plan:
    name: Terraform Plan - Feature
    if: github.ref == 'refs/heads/terraform-dev'
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: environment/dev

    steps:

      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: |
            {
              "clientId": "cc674b5d-a1e6-402f-bd6a-dec7ff2f631d",
              "clientSecret": "-K98Q~FKme2iBLPAUQJPWRuZOws~4F-ip0mgbcEN",
              "subscriptionId": "28b33a86-0366-416d-8614-9dccbe3c193b",
              "tenantId": "0e48a96c-4cf9-4bb4-bf06-2a912f0fc53e"
            }

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Init
      - name: Terraform Init
        run: terraform init

      # Validate
      - name: Terraform Validate
        run: terraform validate

      # Plan
      - name: Terraform Plan
        run: terraform plan